"""Add name column to users table

Revision ID: 835b6c6a5aaf
Revises: 
Create Date: 2025-08-02 10:54:18.414653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835b6c6a5aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
